CREATE TABLE IF NOT EXISTS user
(
    device_id  VARCHAR(255) PRIMARY KEY,
    last_x     FLOAT NOT NULL DEFAULT 0,
    last_y     FLOAT NOT NULL DEFAULT 0,
    last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);